### ISSUE TITLE
Discrepancy in cleaned_docs.csv

### ISSUE THREAD

**Issue by kwalcock** [Allegra-Cohen/grid#12]
Someone could check out the extra line at the top of cleaned_docs.csv with "sentence". It isn't causing this problem, but maybe it adversely affects other things.

**Comment by Allegra-Cohen** [comment]
Do you mean that the current code loads clean lines with header = 0? I think this is the default behavior in the old code loading as well (i.e., read_csv() and read_csv(header = 0) do the same thing).

**Comment by kwalcock** [comment]
This link, https://github.com/Allegra-Cohen/grid/blob/main/process_files/cleaned_docs.csv#L1-L3, doesn't highlight well, but the line
```
0,sentence,sentence
```
does not look legitimate.

**Comment by Allegra-Cohen** [comment]
Sorry, it's definitely not. I assume that came in when I read the corpus in my original code, I used `corpus =  pd.read_csv(path + 'corpus.csv', header = None)` but there was definitely a header. It looks like it would generate the right cleaned_docs.csv now because you have header = 0 everywhere.
