### ISSUE TITLE
Error handling in user input / GET vs PUT POST

### ISSUE THREAD

**Issue by Allegra-Cohen** [Allegra-Cohen/grid#41]
Error handling for user input is a bit scattered. I'm using GET everywhere and Keith suggests PUT/POST is more robust. Not watching for punctuation in some places. Generally need to beat on everything a user could input, including filenames and column stuff.

**Comment by kwalcock** [comment]
This may be done in the meantime.  It's still GET, but the values are placed elsewhere, in the query.
